apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-app
spec:
  selector:
    matchLabels:
      app: team-a
  replicas: 1
  template:
    metadata:
      labels:
        app: team-a
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/agmsb-lab/team-a-repository/team-a-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: team-a-app
spec:
  selector:
    app: team-a
  ports:
  - name: app-port
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer