apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-b-app
  namespace: team-b
spec:
  selector:
    matchLabels:
      app: team-b
  replicas: 1
  template:
    metadata:
      labels:
        app: team-b
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/agmsb-lab/team-b-repository/team-b-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: team-b-app
  namespace: team-b
spec:
  selector:
    app: team-b
  ports:
  - name: app-port
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer